name: test-github-action-dev
# comment
on:
  push:
    branches:
      - develop
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev
        run: echo "deploy dev"
      - name: XXXXXX
        run: echo ${{ github.ref }}
      - name: X222
        run: echo ${{ github }}