name: test-github-action-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev
        run: echo "deploy dev"