name: test-github-action

on:
  push:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev
        if: ${{ github.ref }} == "refs/heads/develop"
        run: echo "deploy dev"

      - name: Deploy prod
        if: ${{ github.ref }} == "refs/heads/main"
        run: echo "deploy prd"
